#####################################################################################
# GitHub Action to generate Checkstyle report.
#
# Workflow starts when:
# 1) issue comment - created
#
# For another bucket, you will need to change the secrets.
#####################################################################################
name: Check-Performance-Regression

on:
  push:
    branches:
      - master
  pull_request:
    branches: '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: 'temurin'

      - name: Checkout patch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          path: ./checkstyle

      - name: Clone JDK 22 Repo
        uses: actions/checkout@v4
        with:
          repository: openjdk/jdk22
          path: ./checkstyle/.ci/jdk22

      - name: Setup local maven cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: checkstyle-maven-cache-${{ hashFiles('**/pom.xml') }}

      - name: Run performance test
        run: |
          cd checkstyle
          bash ./.ci/check-performance-regression.sh